debug: true
info:
  version: 1.0
server:
  port: 8080
spring:
  application:
    name: admin
eureka:
  instance:
    hostname: admin
    preferIpAddress: true 
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE:http://eureka:8761/eureka}   

management:
  security:
    enabled: false      